"""followers

Revision ID: 4c0fcf14b841
Revises: 7a9d9d89ea35
Create Date: 2025-10-21 15:09:04.929924

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4c0fcf14b841'
down_revision = '7a9d9d89ea35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'followers',
        sa.Column('follower_id', sa.Integer(), nullable=False),
        sa.Column('followed_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['followed_id'],
            ['user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['follower_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('follower_id', 'followed_id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
